settings:
  allow-end: false
  permissions-file: configs/permissions.yml
  connection-throttle: 0
  query-plugins: false
  deprecated-verbose: false
spawn-limits:
  monsters: 0
  animals: 0
  water-animals: 0
  ambient: 0
chunk-gc:
  period-in-ticks: 600
  load-threshold: 0
ticks-per:
  animal-spawns: 0
  monster-spawns: 0
  autosave: 6000